Django_level_5/pro_users/my_app/urls.py
from django.urls import path
from . import views

# template urls
app_name = 'my_app'

urlpatterns=[
    path('register/', views.register,name='register'),
    path('user_login', views.user_login,name='user_login'),
]

Django_level_5/pro_users/pro_users/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from my_app import views


urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('logout', views.user_logout,name='logout'),
    path('special/', views.special,name='special')
]

Django_level_5/pro_users/my_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING, )

    #additional

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username

Django_level_5/pro_users/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Django_level_5/pro_users/my_app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm

# this next four line of code is for logins
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'my_app/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in,  NIce!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)


    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'my_app/registration.html',
                       {'user_form':user_form,
                       'profile_form':profile_form,
                       'registered':registered})

# a sepert codes for logins

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account not active')
        else:
            print('Some tried to login and faild!')
            print('Username:{}and password {}'.format(username,password))
            return HttpResponse ('invalid login details supplied')

    else:
        return render(request,'my_app/login.html',{})

Django_level_5/pro_users/templates/my_app/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">



<a class="nav-brand" href="{% url 'index' %}">Home</a>

<a class="nav-link" href="{% url 'admin:index' %}">Admin</a>

<a class="nav-link" href="{% url 'my_app:register' %}">Register</a>

{% if user.is_authenticated  %}

<a class="nav-link" href="{% url 'logout' %}">Logout</a>
{% else  %}
<a class="nav-link" href="{% url 'my_app:user_login' %}">login</a>

{% endif  %}
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>



  </body>
</html>

Django_level_5/pro_users/templates/my_app/index.html
{% extends "my_app/basic.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to Home Page</h1>
  <p>Django Level Five</p>

</div>
{% endblock %}

Django_level_5/pro_users/templates/my_app/login.html
{%  extends 'my_app/basic.html'  %}
{% block body_block %}

<div class="jumbotorn">
  <h1>Please Login </h1>
  <form action="{% url 'my_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" value="" placeholder="Enter Username">


    <label for="password">Password:</label>
    <input type="password" name="password">


    <input type="submit" name="" value="Login">

  </form>
</div>




{%  endblock %}

Django_level_5/pro_users/templates/my_app/registration.html
{% extends "my_app/basic.html" %}
{%  load static   %}
{% block body_block %}

<div class="jumbotron">
  
  <p>Django Level Five</p>
{% if registered %}
<h1>thank you for registering</h1>
{%  else %}
<h1>Register here!</h1>
<h2>fill out the form</h2>
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" name="" value="Register">
</form>
{% endif %}
</div>
{% endblock %}